<?php
require_once __DIR__ . '/../config/app.php';
require_once __DIR__ . '/../includes/functions.php';
$stats = function_exists('getPlatformStats') ? getPlatformStats() : ['verified_rooms'=>0,'landlords'=>0,'tenants'=>0,'contracts'=>0];
$page_title = 'About Us';
require_once __DIR__ . '/../includes/header.php';
?>
<section class="page-shell"><div class="container page-content page-content-wide"><div class="page-hero"><span class="page-eyebrow">About Gharbeti</span><h1>Nepal's broker-free rental platform built around trust.</h1><p>We help tenants and landlords connect directly with clearer profiles, verified listings, and digital contracts that reduce friction for both sides.</p></div><div class="card-grid card-grid-2"><article class="page-panel"><h2>Our Story</h2><p>Gharbeti started with a simple problem: too many renters in Nepal still depend on unreliable brokers, incomplete listings, and verbal agreements that create confusion later.</p><p>We built Gharbeti to make renting feel more direct and accountable with clearer room details, direct messaging, and digital contracts.</p><p>The goal is practical: help people find the right room faster and start rental relationships with fewer surprises.</p></article><aside class="page-panel page-panel-soft"><h2>Community Snapshot</h2><div class="metric-grid"><div class="metric-card"><strong><?php echo formatNumber((int) $stats['verified_rooms']); ?>+</strong><span>Verified rooms</span></div><div class="metric-card"><strong><?php echo formatNumber((int) $stats['landlords']); ?>+</strong><span>Landlords</span></div><div class="metric-card"><strong><?php echo formatNumber((int) $stats['tenants']); ?>+</strong><span>Tenants</span></div><div class="metric-card"><strong><?php echo formatNumber((int) $stats['contracts']); ?>+</strong><span>Contracts</span></div></div><div class="info-callout"><h3>Our mission</h3><p>Make room discovery in Nepal safer, more transparent, and easier to trust from the first message to the signed agreement.</p></div></aside></div><div class="page-panel"><h2>What We Care About</h2><div class="card-grid card-grid-3"><article class="mini-card"><i class="fas fa-shield-alt"></i><h3>Trust First</h3><p>Verification, reputation signals, and clearer profiles help users make more confident decisions.</p></article><article class="mini-card"><i class="fas fa-comments"></i><h3>Direct Communication</h3><p>Tenants and landlords can talk directly without unnecessary middlemen adding cost and confusion.</p></article><article class="mini-card"><i class="fas fa-file-signature"></i><h3>Clear Agreements</h3><p>Digital contracts make expectations visible before move-in and give both sides a proper record.</p></article></div></div><div class="page-panel page-cta"><h2>Have questions about the platform?</h2><p>We keep building Gharbeti around the real problems renters and landlords face every day.</p><div class="tag-row"><a href="<?php echo SITE_URL; ?>/pages/contact.php" class="btn-primary">Contact Us</a><a href="<?php echo SITE_URL; ?>/pages/faq.php" class="btn-outline">Read FAQ</a></div></div></div></section>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
