<?php
require_once __DIR__ . '/../config/app.php';
require_once __DIR__ . '/../includes/functions.php';
$blog_posts = [
    ['id' => 1, 'title' => 'How to Avoid Rental Scams in Nepal', 'excerpt' => 'A practical checklist for spotting suspicious listings, pressure tactics, and unsafe payment requests.', 'author' => 'Gharbeti Team', 'date' => '2026-02-15', 'category' => 'Safety', 'read_time' => 5],
    ['id' => 2, 'title' => 'What a Good Rental Agreement Should Always Include', 'excerpt' => 'The most important clauses to review before you sign any room rental contract.', 'author' => 'Gharbeti Team', 'date' => '2026-02-09', 'category' => 'Legal', 'read_time' => 6],
    ['id' => 3, 'title' => 'How Landlords Can Earn More Trust Online', 'excerpt' => 'Simple profile and listing upgrades that can improve response quality and reduce wasted chats.', 'author' => 'Gharbeti Team', 'date' => '2026-01-30', 'category' => 'Landlords', 'read_time' => 4],
    ['id' => 4, 'title' => 'Student-Friendly Areas to Consider Around Kathmandu Valley', 'excerpt' => 'A quick guide to balancing commute time, budget, and neighborhood feel.', 'author' => 'Gharbeti Team', 'date' => '2026-01-21', 'category' => 'Location Guide', 'read_time' => 7],
    ['id' => 5, 'title' => 'How Trust Scores Work on Gharbeti', 'excerpt' => 'What increases trust, what weakens it, and how users can build a stronger profile over time.', 'author' => 'Gharbeti Team', 'date' => '2026-01-12', 'category' => 'Product Guide', 'read_time' => 3],
    ['id' => 6, 'title' => 'Preparing Your Room Listing Photos the Right Way', 'excerpt' => 'A quick visual checklist for landlords who want listings that feel credible and complete.', 'author' => 'Gharbeti Team', 'date' => '2025-12-28', 'category' => 'Listing Tips', 'read_time' => 4],
];
$page_title = 'Blog';
require_once __DIR__ . '/../includes/header.php';
?>
<section class="page-shell"><div class="container page-content page-content-wide"><div class="page-hero"><span class="page-eyebrow">Blog</span><h1>Guides, explainers, and practical rental advice.</h1><p>We publish simple, useful content for tenants, landlords, and anyone navigating the rental process in Nepal.</p></div><?php $featured = $blog_posts[0]; ?><article class="page-panel page-featured-post"><div><span class="pill-tag">Featured</span><h2><?php echo htmlspecialchars($featured['title']); ?></h2><p><?php echo htmlspecialchars($featured['excerpt']); ?></p><div class="meta-row"><span><?php echo htmlspecialchars($featured['author']); ?></span><span><?php echo date('M d, Y', strtotime($featured['date'])); ?></span><span><?php echo (int) $featured['read_time']; ?> min read</span></div><a href="<?php echo SITE_URL; ?>/pages/blog-post.php?id=<?php echo (int) $featured['id']; ?>" class="btn-primary">Read Article</a></div><div class="feature-illustration"><i class="fas fa-newspaper"></i></div></article><div class="card-grid card-grid-3"><?php foreach (array_slice($blog_posts, 1) as $post): ?><article class="page-panel blog-card"><span class="pill-tag pill-tag-soft"><?php echo htmlspecialchars($post['category']); ?></span><h2><?php echo htmlspecialchars($post['title']); ?></h2><p><?php echo htmlspecialchars($post['excerpt']); ?></p><div class="meta-row"><span><?php echo htmlspecialchars($post['author']); ?></span><span><?php echo date('M d, Y', strtotime($post['date'])); ?></span></div><a href="<?php echo SITE_URL; ?>/pages/blog-post.php?id=<?php echo (int) $post['id']; ?>" class="text-link">Read more</a></article><?php endforeach; ?></div></div></section>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
